ZGD.Web/Controllers/CtrlController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ZGD.Web.Controllers
{
    public class CtrlController : BaseController
    {
        /// <summary>
        /// 站点头部
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public ActionResult Top(string menuID = "0")
        {
            BLL.Channel cBll = new BLL.Channel();
            ViewBag.menuID = menuID;
            ViewBag.NavList = cBll.GetList(" IsDelete=0 and IsNav=1").Tables[0];

            return View("~/Views/Shared/_Top.cshtml");
        }

        /// <summary>
        /// 站点底部
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public ActionResult Footer()
        {
            return View("~/Views/Shared/_Footer.cshtml");
        }
    }
}

ZGD.Web/Controllers/ZTController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;

namespace ZGD.Web.Controllers
{
    public class ZTController : BaseController
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult Index(int page = 1)
        {
            ZGD.BLL.Channel cBll = new ZGD.BLL.Channel();
            DataSet ds = cBll.GetList(0, " ParentId=21 and KindId=2 and IsDelete=0", " Id desc");
            DataSet ys = cBll.GetZtYear();

            ViewBag.ZtList = ds != null && ds.Tables[0].Rows.Count > 0 ? ds.Tables[0] : null;
            ViewBag.Year = ys != null && ys.Tables[0].Rows.Count > 0 ? ys.Tables[0] : null;
            return View();
        }
    }
}

ZGD.Web/Views/ZT/Index.cshtml
@{
    ViewBag.Title = ViewBag.Type;
    ViewBag.Keywords = "中国致公党重庆市委员会";
    ViewBag.Description = "中国致公党重庆市委员会";
}

@using ZGD.Common
@using System.Data
@{Html.RenderAction("Top", "Ctrl", new { menuID = ViewBag.TypeID });}

<div class="con_bg main">
    <div class="index_top" style="height:auto;">
        <div class="title"><span>您的位置：<a href="/">首页</a> <em>&gt;</em></span> 专题报道</div>

        <div class="index_top_con">
            <ul class="news_page">
                @foreach (DataRow item in ViewBag.ZtList.Rows)
                {
                    <li><a href="/articlepage/21-@(ViewBag.TypeID)-@(item["Id"].ToString())" title="@(item["Title"].ToString())">@(item["Title"].ToString())</a></li>
                }
            </ul>
            <div class="pager">
                @Html.Raw(ViewBag.Pager)
            </div>
        </div>

        @*<div class="index_top_con">
                @foreach (DataRow year in ViewBag.Year.Rows)
                {
                    <div class="zt_item">
                        <h3><span>@(year["y"].ToString())年专题</span></h3>
                        <ul class="zt_page">
                            @foreach (DataRow item in ViewBag.ZtList.Rows)
                            {
                                <li><a href="/articlepage/21-@(ViewBag.TypeID)-@(item["Id"].ToString())" title="@(item["Title"].ToString())"><img src="@(item["ImgUrl"].ToString())" alt="@(item["Title"].ToString())" /></a></li>
                            }
                        </ul>
                    </div>
                }
            </div>*@
        <div class="space30"></div>
        <hr class="page_hr" />
    </div>
</div>